import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Checkbox, FormControlLabel, Grid, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { apiClient } from '../api/client';

type Statement={id:string;accountId:string;periodStart:string;periodEnd:string;closingBalance:number;currency:string};
type Dispute={id:string;transactionId:string;amount:number;currency:string;status:string};
type Notice={id:string;title:string;message:string;readAt?:string;createdAt:string};
type Preferences={inApp:boolean;email:boolean;security:boolean;payments:boolean;statements:boolean;disputes:boolean};
const defaults:Preferences={inApp:true,email:true,security:true,payments:true,statements:true,disputes:true};

export function PhaseSixPanel({accounts}:{accounts:Array<{id:string;nickname:string;currency:string;balance?:{currentBalance:string}|null}>}){
 const [statements,setStatements]=useState<Statement[]>([]),[disputes,setDisputes]=useState<Dispute[]>([]),[notices,setNotices]=useState<Notice[]>([]),[prefs,setPrefs]=useState(defaults),[error,setError]=useState('');
 const first=accounts[0]; const today=new Date().toISOString().slice(0,10); const monthStart=today.slice(0,8)+'01';
 const [statement,setStatement]=useState({accountId:'',periodStart:monthStart,periodEnd:today,openingBalance:'0',closingBalance:'0',currency:'USD'});
 const [dispute,setDispute]=useState({transactionId:'',accountId:'',reason:'CARD_PURCHASE',details:'',amount:'',currency:'USD'});
 const load=async()=>{try{const [s,d,n,p]=await Promise.all([apiClient.get('/statements'),apiClient.get('/disputes'),apiClient.get('/notifications'),apiClient.get('/notification-preferences')]);setStatements(s.data);setDisputes(d.data);setNotices(n.data);setPrefs(p.data);}catch(e){setError('Phase 6 data is temporarily unavailable.');}};
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(first&&!statement.accountId){setStatement(v=>({...v,accountId:first.id,currency:first.currency,openingBalance:first.balance?.currentBalance??'0',closingBalance:first.balance?.currentBalance??'0'}));setDispute(v=>({...v,accountId:first.id,currency:first.currency}));}},[first]);
 const createStatement=async()=>{setError('');try{await apiClient.post('/statements',{...statement,openingBalance:Number(statement.openingBalance),closingBalance:Number(statement.closingBalance)});await load();}catch{setError('Unable to create statement. Check the dates and balances.');}};
 const createDispute=async()=>{setError('');try{await apiClient.post('/disputes',{...dispute,amount:Number(dispute.amount)});setDispute(v=>({...v,transactionId:'',details:'',amount:''}));await load();}catch{setError('Unable to submit dispute. Check the transaction and amount.');}};
 const download=async(id:string)=>{const r=await apiClient.get(`/statements/${id}/document`,{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download='novabank-statement.txt';a.click();URL.revokeObjectURL(url);};
 return <Stack spacing={3}>{error&&<Alert severity="error">{error}</Alert>}<Grid container spacing={3}>
  <Grid item xs={12} lg={6}><Card elevation={0} className="summary-card"><CardContent><Stack spacing={2}><Typography variant="h6" fontWeight={900}>Statements & secure documents</Typography><TextField select label="Account" value={statement.accountId} onChange={e=>setStatement({...statement,accountId:e.target.value})}>{accounts.map(a=><MenuItem key={a.id} value={a.id}>{a.nickname}</MenuItem>)}</TextField><Stack direction="row" spacing={2}><TextField type="date" label="From" InputLabelProps={{shrink:true}} value={statement.periodStart} onChange={e=>setStatement({...statement,periodStart:e.target.value})}/><TextField type="date" label="To" InputLabelProps={{shrink:true}} value={statement.periodEnd} onChange={e=>setStatement({...statement,periodEnd:e.target.value})}/></Stack><Button variant="contained" disabled={!statement.accountId} onClick={createStatement}>Generate demo statement</Button>{statements.map(s=><Box key={s.id}><Typography>{s.periodStart} – {s.periodEnd} · {s.currency} {s.closingBalance}</Typography><Button size="small" onClick={()=>download(s.id)}>Download encrypted document</Button></Box>)}</Stack></CardContent></Card></Grid>
  <Grid item xs={12} lg={6}><Card elevation={0} className="summary-card"><CardContent><Stack spacing={2}><Typography variant="h6" fontWeight={900}>Dispute a transaction</Typography><Alert severity="info">Eligible demo disputes up to $500 receive an automatic provisional credit. Credits are never customer-triggered.</Alert><TextField label="Transaction ID" value={dispute.transactionId} onChange={e=>setDispute({...dispute,transactionId:e.target.value})}/><TextField label="Amount" type="number" value={dispute.amount} onChange={e=>setDispute({...dispute,amount:e.target.value})}/><TextField label="What happened?" multiline minRows={3} value={dispute.details} onChange={e=>setDispute({...dispute,details:e.target.value})}/><Button variant="contained" disabled={!dispute.transactionId||!dispute.amount||!dispute.details.trim()} onClick={createDispute}>Submit dispute</Button>{disputes.map(d=><Box key={d.id}><Typography>{d.transactionId} · {d.currency} {d.amount}</Typography><Typography color="text.secondary">{d.status}</Typography></Box>)}</Stack></CardContent></Card></Grid>
 </Grid><Card elevation={0} className="summary-card"><CardContent><Stack spacing={2}><Typography variant="h6" fontWeight={900}>Notifications</Typography>{notices.length===0?<Typography color="text.secondary">No notifications yet.</Typography>:notices.map(n=><Box key={n.id}><Typography fontWeight={700}>{n.title}</Typography><Typography color="text.secondary">{n.message}</Typography>{!n.readAt&&<Button size="small" onClick={async()=>{await apiClient.post(`/notifications/${n.id}/read`);await load();}}>Mark read</Button>}</Box>)}<Typography fontWeight={800}>Notification preferences</Typography><Stack direction="row" flexWrap="wrap">{(Object.keys(prefs) as Array<keyof Preferences>).map(k=><FormControlLabel key={k} control={<Checkbox checked={prefs[k]} onChange={async e=>{const next={...prefs,[k]:e.target.checked};setPrefs(next);await apiClient.put('/notification-preferences',next);}}/>} label={k}/>)}</Stack></Stack></CardContent></Card></Stack>;
}
