package com.novabank.risk.service;
import com.fasterxml.jackson.databind.ObjectMapper; import com.novabank.risk.api.RiskModels.*; import com.novabank.risk.config.RiskProperties; import io.micrometer.core.instrument.*; import org.springframework.dao.DuplicateKeyException; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.sql.ResultSet; import java.time.Instant; import java.util.*;
@Service public class RiskOperationsService {
 private final JdbcTemplate jdbc; private final RiskEngine engine; private final RiskProperties props; private final ObjectMapper json; private final MeterRegistry metrics; private final ReviewedPaymentClient payments;
 public RiskOperationsService(JdbcTemplate j,RiskEngine e,RiskProperties p,ObjectMapper o,MeterRegistry m,ReviewedPaymentClient pc){jdbc=j;engine=e;props=p;json=o;metrics=m;payments=pc;}
 @Transactional public AssessmentResponse assess(AssessmentRequest r){var old=findByOperation(r.operationReference());if(old.isPresent())return old.get(); long start=System.nanoTime(); var x=engine.evaluate(r); var id=UUID.randomUUID();var now=Instant.now();
  jdbc.update("insert into risk_assessments(id,operation_reference,customer_id,operation_type,amount,score,decision,triggered_rules,customer_reason,analyst_explanation,rule_version,correlation_id,created_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?)",id,r.operationReference(),r.customerId(),r.operationType(),r.amount(),x.score(),x.decision().name(),String.join(",",x.rules()),x.safeReason(),x.explanation(),props.ruleVersion(),r.correlationId(),java.sql.Timestamp.from(now));
  outbox("risk.assessment.completed",id,r.correlationId(),Map.of("assessmentId",id,"operationReference",r.operationReference(),"decision",x.decision()));
  if(x.decision()!=Decision.ALLOW) createAlertAndCase(id,x.decision(),r.correlationId()); metrics.counter("risk_assessments_total").increment(); metrics.counter("risk_decisions_total","decision",x.decision().name()).increment(); metrics.timer("risk_evaluation_latency").record(System.nanoTime()-start,java.util.concurrent.TimeUnit.NANOSECONDS);
  return new AssessmentResponse(id,r.customerId(),r.operationReference(),x.score(),x.decision(),x.rules(),x.safeReason(),x.explanation(),props.ruleVersion(),now,r.correlationId()); }
 private void createAlertAndCase(UUID assessment,Decision d,UUID corr){var alert=UUID.randomUUID();var c=UUID.randomUUID();String priority=d==Decision.DENY?"HIGH":"MEDIUM";jdbc.update("insert into risk_alerts(id,assessment_id,priority) values(?,?,?)",alert,assessment,priority);jdbc.update("insert into fraud_cases(id,alert_id,priority,status) values(?,?,?,'OPEN')",c,alert,priority);history(c,null,"OPEN","system","Created from risk alert");outbox("risk.alert.created",alert,corr,Map.of("alertId",alert,"priority",priority));outbox("risk.case.created",c,corr,Map.of("caseId",c,"priority",priority));}
 public Optional<AssessmentResponse> findByOperation(String op){return jdbc.query("select * from risk_assessments where operation_reference=?",this::map,op).stream().findFirst();}
 public List<Map<String,Object>> cases(String status,String priority){return jdbc.queryForList("select c.*,a.assessment_id,r.operation_reference,r.decision,r.score from fraud_cases c join risk_alerts a on a.id=c.alert_id join risk_assessments r on r.id=a.assessment_id where (cast(? as varchar) is null or c.status=?) and (cast(? as varchar) is null or c.priority=?) order by c.created_at desc",status,status,priority,priority);}
 @Transactional public void act(UUID id,CaseActionRequest r,String actor,String auth,UUID corr){var rows=jdbc.queryForList("select c.*,ra.operation_reference from fraud_cases c join risk_alerts a on a.id=c.alert_id join risk_assessments ra on ra.id=a.assessment_id where c.id=? for update",id);if(rows.isEmpty())throw new IllegalArgumentException("Case not found");var row=rows.getFirst();var old=String.valueOf(row.get("status"));String next=r.status()==null?old:r.status();if("PAYMENT_APPROVED".equals(r.resolution())||"PAYMENT_REJECTED".equals(r.resolution())){var ref=String.valueOf(row.get("operation_reference"));if(!ref.startsWith("payment:"))throw new IllegalArgumentException("Case is not linked to a payment");payments.decide(UUID.fromString(ref.substring(8)),"PAYMENT_APPROVED".equals(r.resolution()),auth,corr);}jdbc.update("update fraud_cases set assigned_to=coalesce(?,assigned_to),status=?,resolution=coalesce(?,resolution),resolved_at=case when ?='RESOLVED' then now() else resolved_at end where id=?",r.assignee(),next,r.resolution(),next,id);if(!old.equals(next))history(id,old,next,actor,r.resolution());if(r.note()!=null&&!r.note().isBlank())jdbc.update("insert into case_notes(id,case_id,author,note) values(?,?,?,?)",UUID.randomUUID(),id,actor,r.note().trim());audit(actor,"CASE_ACTION","CASE",id,corr,"status="+next);String event="PAYMENT_APPROVED".equals(r.resolution())?"risk.payment.approved":"PAYMENT_REJECTED".equals(r.resolution())?"risk.payment.rejected":"RESOLVED".equals(next)?"risk.case.resolved":"risk.case.assigned";outbox(event,id,corr,Map.of("caseId",id,"status",next));}
 @Transactional public UUID watch(WatchlistRequest r,String actor,UUID corr){var id=UUID.randomUUID();jdbc.update("insert into watchlist_entries(id,subject_type,subject_reference,reason,created_by) values(?,?,?,?,?)",id,r.subjectType().toUpperCase(),r.subjectReference(),r.reason(),actor);audit(actor,"WATCHLIST_ADD","WATCHLIST",id,corr,"subjectType="+r.subjectType());return id;}
 public List<Map<String,Object>> watchlist(){return jdbc.queryForList("select id,subject_type,subject_reference,reason,active,created_by,created_at from watchlist_entries order by created_at desc");}
 private AssessmentResponse map(ResultSet s,int n)throws java.sql.SQLException{return new AssessmentResponse(s.getObject("id",UUID.class),s.getObject("customer_id",UUID.class),s.getString("operation_reference"),s.getInt("score"),Decision.valueOf(s.getString("decision")),s.getString("triggered_rules").isBlank()?List.of():List.of(s.getString("triggered_rules").split(",")),s.getString("customer_reason"),s.getString("analyst_explanation"),s.getString("rule_version"),s.getTimestamp("created_at").toInstant(),s.getObject("correlation_id",UUID.class));}
 private void history(UUID c,String old,String next,String actor,String reason){jdbc.update("insert into case_status_history(id,case_id,previous_status,new_status,actor,reason) values(?,?,?,?,?,?)",UUID.randomUUID(),c,old,next,actor,reason);}
 private void audit(String actor,String action,String type,UUID id,UUID corr,String details){jdbc.update("insert into risk_audit_history(id,actor,action,target_type,target_id,correlation_id,details) values(?,?,?,?,?,?,?)",UUID.randomUUID(),actor,action,type,id,corr,details);}
 private void outbox(String type,UUID aggregate,UUID corr,Object payload){try{jdbc.update("insert into risk_outbox(id,event_type,aggregate_id,payload,correlation_id) values(?,?,?,?,?)",UUID.randomUUID(),type,aggregate,json.writeValueAsString(payload),corr);}catch(Exception e){throw new IllegalStateException(e);}}
}
