import { Alert, Box, Button, Card, CardContent, Stack, TextField, Typography } from '@mui/material';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Link as RouterLink } from 'react-router-dom';
import { apiClient } from '../api/client';

interface ResetPasswordForm {
  resetToken: string;
  newPassword: string;
  confirmPassword: string;
}

export function ResetPasswordPage() {
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const { register, handleSubmit, watch, formState: { errors, isSubmitting } } = useForm<ResetPasswordForm>();

  const onSubmit = async ({ confirmPassword: _confirmPassword, ...values }: ResetPasswordForm) => {
    setError(null);
    setMessage(null);
    try {
      const response = await apiClient.post<{ message: string }>('/auth/reset-password', values);
      setMessage(response.data.message);
    } catch (apiError: any) {
      setError(apiError.response?.data?.message ?? 'Unable to reset password');
    }
  };

  return (
    <Box className="center-shell">
      <Card className="narrow-card" elevation={0}>
        <CardContent>
          <Typography component="h1" variant="h4" fontWeight={800}>Set a new password</Typography>
          <Typography color="text.secondary" marginBottom={3}>
            Paste a mock reset token generated by the backend, then choose a replacement password.
          </Typography>
          {message && <Alert severity="success" sx={{ mb: 2 }}>{message}</Alert>}
          {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
          <Stack component="form" spacing={2} onSubmit={handleSubmit(onSubmit)} noValidate>
            <TextField
              label="Reset token"
              error={Boolean(errors.resetToken)}
              helperText={errors.resetToken?.message}
              {...register('resetToken', { required: 'Reset token is required' })}
            />
            <TextField
              label="New password"
              type="password"
              autoComplete="new-password"
              error={Boolean(errors.newPassword)}
              helperText={errors.newPassword?.message}
              {...register('newPassword', {
                required: 'Password is required',
                minLength: { value: 12, message: 'Use at least 12 characters' },
                pattern: {
                  value: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).+$/,
                  message: 'Include uppercase, lowercase, number, and symbol'
                }
              })}
            />
            <TextField
              label="Confirm new password"
              type="password"
              autoComplete="new-password"
              error={Boolean(errors.confirmPassword)}
              helperText={errors.confirmPassword?.message}
              {...register('confirmPassword', {
                required: 'Confirm your password',
                validate: (value) => value === watch('newPassword') || 'Passwords must match'
              })}
            />
            <Button type="submit" variant="contained" disabled={isSubmitting}>
              {isSubmitting ? 'Resetting...' : 'Reset password'}
            </Button>
            <Button component={RouterLink} to="/login">Back to sign in</Button>
          </Stack>
        </CardContent>
      </Card>
    </Box>
  );
}
