import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { useEffect, useState } from 'react'; import { Link } from 'react-router-dom'; import { apiClient } from '../api/client';
type RiskCase={id:string;priority:string;status:string;assigned_to?:string;operation_reference:string;decision:string;score:number};
export function RiskOperationsPage(){const[cases,setCases]=useState<RiskCase[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[status,setStatus]=useState('');const[priority,setPriority]=useState('');const[selected,setSelected]=useState<RiskCase|null>(null);const[note,setNote]=useState('');const[submitting,setSubmitting]=useState(false);
 const load=async()=>{setLoading(true);setError('');try{const r=await apiClient.get('/risk/cases',{params:{status:status||undefined,priority:priority||undefined}});setCases(r.data)}catch(e){setError('Unable to load the risk queue.')}finally{setLoading(false)}};useEffect(()=>{void load()},[status,priority]);
 const action=async(resolution:string)=>{if(!selected||submitting)return;if(!window.confirm(`Confirm ${resolution==='PAYMENT_APPROVED'?'approval':'rejection'} for this payment?`))return;setSubmitting(true);try{await apiClient.post(`/risk/cases/${selected.id}/actions`,{status:'RESOLVED',resolution,note});setSelected(null);setNote('');await load()}catch(e){setError('The action could not be completed. Refresh before retrying.')}finally{setSubmitting(false)}};
 return <Box className="dashboard-shell"><Stack spacing={3}><Stack direction="row" justifyContent="space-between"><Box><Typography variant="h4" fontWeight={900}>Risk Operations</Typography><Typography color="text.secondary">Deterministic payment reviews and investigation cases</Typography></Box><Button component={Link} to="/dashboard">Customer dashboard</Button></Stack>
 <Stack direction={{xs:'column',sm:'row'}} spacing={2}><TextField select label="Status" value={status} onChange={e=>setStatus(e.target.value)} sx={{minWidth:180}}><MenuItem value="">All statuses</MenuItem>{['OPEN','ASSIGNED','INVESTIGATING','AWAITING_CUSTOMER','RESOLVED','ESCALATED'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField select label="Priority" value={priority} onChange={e=>setPriority(e.target.value)} sx={{minWidth:180}}><MenuItem value="">All priorities</MenuItem>{['LOW','MEDIUM','HIGH'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Stack>
 {error&&<Alert severity="error" action={<Button onClick={load}>Retry</Button>}>{error}</Alert>}{loading?<CircularProgress/>:cases.length===0?<Alert severity="info">No cases match these filters.</Alert>:cases.map(c=><Card key={c.id} variant="outlined"><CardContent><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Typography fontWeight={800}>{c.operation_reference}</Typography><Typography color="text.secondary">Risk score {c.score} · {c.decision}</Typography></Box><Stack direction="row" spacing={1} alignItems="center"><Chip label={c.priority} color={c.priority==='HIGH'?'error':'warning'}/><Chip label={c.status}/><Button onClick={()=>setSelected(c)}>Investigate</Button></Stack></Stack></CardContent></Card>)}
 <Dialog open={!!selected} onClose={()=>!submitting&&setSelected(null)} fullWidth><DialogTitle>Case review</DialogTitle><DialogContent><Stack spacing={2} mt={1}><Alert severity="warning">Internal analyst information. Do not disclose rule thresholds or notes to customers.</Alert><Typography>Decision: {selected?.decision} · Score: {selected?.score}</Typography><TextField label="Append-only analyst note" multiline minRows={3} value={note} onChange={e=>setNote(e.target.value)} inputProps={{maxLength:2000}}/></Stack></DialogContent><DialogActions><Button onClick={()=>setSelected(null)} disabled={submitting}>Cancel</Button><Button color="error" onClick={()=>action('PAYMENT_REJECTED')} disabled={submitting||!note.trim()}>Reject payment</Button><Button onClick={()=>action('PAYMENT_APPROVED')} disabled={submitting||!note.trim()}>Approve payment</Button></DialogActions></Dialog></Stack></Box>}
